package mergepr

import "errors"

// Sentinel errors. Callers and tests match them with errors.Is.
var (
	errNoRunner           = errors.New("no command runner")
	errInvalidPRArg       = errors.New("invalid PR argument")
	errInvalidRemote      = errors.New("origin is not a GitHub remote")
	errRemoteMismatch     = errors.New("origin fetch and push URLs name different repositories")
	errRepoMismatch       = errors.New("gh selects a repository other than origin")
	errUnsupportedConfig  = errors.New("unsupported git config can rewrite a remote URL")
	errDetachedHead       = errors.New("HEAD is detached")
	errInvalidBranch      = errors.New("unsafe or invalid branch name")
	errDirtyWorktree      = errors.New("worktree is not clean")
	errHeadBranchMismatch = errors.New("local head branch does not match headRefOid")
	errPRNotOpen          = errors.New("PR is not open")
	errPRNotMerged        = errors.New("PR is not merged")
	errMergeQueued        = errors.New("PR is queued for merge, not merged yet")
	errCrossRepository    = errors.New("cross-repository PRs are not supported")
	errTooLarge           = errors.New("input is too large to draft from safely")
	errChecksFailed       = errors.New("CI checks failed")
	errInvalidState       = errors.New("invalid state")
	errHeadDrift          = errors.New("PR head changed after prepare")
	errBaseDrift          = errors.New("PR base changed after prepare")
	errInvalidSubject     = errors.New("squash subject is not a non-empty single line")
	errInvalidPath        = errors.New("invalid file path")
	errNoMergeCommit      = errors.New("merge commit was not recorded")
	errMergeMissing       = errors.New("merged commit is not in the base branch")
	errLocalBranchDrift   = errors.New("local head branch moved")
	errBranchCheckedOut   = errors.New("local head branch is checked out in another worktree")
	errBaseCheckedOut     = errors.New("base branch is checked out in another worktree; run from that worktree or switch it to another branch")
	errBaseNotCurrent     = errors.New("local base branch is not at origin")
	errToolChanged        = errors.New("the merge tool differs from the PR's base revision")
	errCommandChanged     = errors.New("the command definition in this checkout differs from main")
	errMergeCleanup       = errors.New("merge succeeded but cleanup failed")
	errWorkDirInWorktree  = errors.New("work directory is inside the repository worktree")
	errInsecureWorkDir    = errors.New("work directory must be owned by the current user and not writable by group or other")
	errNoWorktree         = errors.New("not inside a git worktree")
	errToolNotFound       = errors.New("command not found on the trusted PATH")
	errBaseRePin          = errors.New("the base branch moved since prepare; run prepare again")
	errBinaryStale        = errors.New("the mergepr binary is not the current main revision")
)
